Repository sandstreamdev/eoc, pull requests merged in 2019-08, with the labels that each got.

#264 [EOC-400] To big avatar placeholder in user bar dropdown menu
  client/src/app/styles/_mixins.scss
  client/src/common/components/Avatar.scss
Labels: BACKLOG, BUG

#267 Add fix to AuthorizationActionTypes
  client/src/locales/en.json
  client/src/modules/user/UserProfile/UserProfile.jsx
  client/src/modules/user/model/actions.js
Labels: HOTFIX

#268 [EOC-BUG] Add longer pingTimeout to prevent from disconnection
  server/common/variables.js
  server/sockets/index.js
Labels: BUG, PREVIOUS-SPRINT

#273 [EOC-414] Bug remove deleted cohort from archived cohorts for the second owner on a cohorts view
  server/sockets/helpers/index.js
Labels: BACKLOG

#274 [EOC-413] While creating shared list on cohort view creating second as limited causes creation of shared
  client/src/modules/cohort/index.jsx
Labels: BACKLOG, BUG

#277 [EOC-418] During editing, the displayed value changes and the previous status/value appears
  client/src/modules/cohort/components/CohortHeader.jsx
Labels: BUG, CURRENT-SPRINT

#281 [EOC-418] During editing, the displayed value changes and the previous status/value appears
  client/src/modules/list/components/ListHeader.jsx
Labels: BUG, CURRENT-SPRINT

#282 [EOC-397] Activities - to long item name causes horizontal scroll within activities box
  client/src/common/components/Activities/components/Activity.jsx
  client/src/common/components/Activities/components/Activity.scss
Labels: BUG, CURRENT-SPRINT

#283 [EOC-377] Add routes for reseting password, confirmation account for logged user
  client/src/app/components/Layout/Layout.jsx
Labels: CURRENT-SPRINT

#284 [EOC-433] Add backend validation for name for creating list
  server/controllers/list.js
Labels: BUG, CURRENT-SPRINT

#295 [EOC-444] There is no notification when the session has expired when the user changed the password
  server/models/item.model.js
Labels: BUG, CURRENT-SPRINT

#298 [EOC-436] Migrate DB to fix item model
  server/migrations/20190828104112-0.0.4.js
  server/models/item.model.js
Labels: CURRENT-SPRINT

#297 [EOC-437] Move unlockLocks from midleware to helpers directory
  server/common/utils/unlockLocks.js
  server/index.js
Labels: CURRENT-SPRINT
