Repository sandstreamdev/eoc, pull requests merged in 2019-10, with the labels that each got.

#368 [EOC-514] 'X' sign should be visible in filter field only if user entered something
  client/src/common/components/Filter.jsx
Labels: IMPROVEMENT

#370 [EOC-516] Disable getting lists from archived cohorts by getAvailableLists controller
  server/controllers/list.js
Labels: BUG

#373 [EOC-517] Adding/removing/description is always saved as an 'edit activity'
  server/controllers/list.js
Labels: BUG

#380 [EOC-526] Votes count doesn't update via socket
  server/controllers/list.js
Labels: BUG

#395 [EOC-521][FIX] Prevent displaying resource if undefined in ResourcePanel component
  client/src/modules/user/UserProfile/ResourcePanel.jsx
Labels: BUG, HOTFIX

#396 [EOC-521] [HOT-FIX] Remove user account issue with deleted resources
  server/common/utils/userUtils.js
Labels: BUG, HOTFIX

#393 [EOC-549] Bug disable remove faving for archived lists
  client/src/common/components/ListViewItem.jsx
Labels: BUG

#407 [EOC-555] Remove fav icon on tile view
  client/src/common/components/TilesViewItem.jsx
Labels: BUG

#410 [EOC-558] Add listeners when dialog is visible not mounted
  client/src/common/components/FormDialog.jsx
Labels: BUG, HOTFIX

#412 [EOC-556] Restoring cohort/list doesn't send lists via socket
  server/common/utils/helpers.js
  server/controllers/list.js
Labels: BUG

#413 [EOC-557] Archive cohort should set all cohort's list as archived
  server/common/utils/helpers.js
Labels: BUG

#423 [EOC-570] The list is visible on the dashboard for members after change "Shared" to "Limited"
  server/sockets/list.js
Labels: BUG

#431 [EOC-582] Description from previous created Sack or Cohort cannot be copied for next created
  client/src/common/components/FormDialog.jsx
  client/src/modules/cohort/components/Cohorts.jsx
  client/src/modules/cohort/index.jsx
  client/src/modules/dashboard/index.jsx
Labels: BUG

#436 [EOC-587] Fix all submit buttons styles on Safari
  client/src/app/styles/_buttons.scss
  client/src/app/styles/_forms.scss
  client/src/common/components/Activities/Activities.scss
  client/src/common/components/DescriptionTextarea.scss
  client/src/common/components/NameInput.scss
  client/src/modules/list/components/Items/InputBar/InputBar.scss
  client/src/modules/user/AuthBox/components/PasswordChangeForm.scss
  client/src/modules/user/AuthBox/components/SignInForm.scss
  client/src/modules/user/AuthBox/components/SignUpForm.scss
Labels: BUG

#438 [EOC-592] Notification timer doesn't work when session expires
  client/src/locales/en.json
  client/src/modules/notification/components/NotificationWithTimer.jsx
Labels: BUG

#440 Topbar icons alignment hotfix
  client/src/common/components/Activities/Activities.scss
Labels: HOTFIX
