Repository sandstreamdev/eoc, pull requests merged in 2019-09, with the labels that each got.

#300 [EOC-409] [IMPROVEMENT] Parametrize password requirments localized messages
  client/src/common/constants/enums.js
  client/src/common/utils/helpers.js
  client/src/locales/en.json
  client/src/modules/user/AuthBox/components/AuthInput.jsx
  client/src/modules/user/AuthBox/components/ValidationInput.jsx
Labels: CURRENT-SPRINT

#303 [EOC-312] Fill out description and update Readme.md file
  README.md
Labels: CURRENT-SPRINT

#307 [HOTFIX] FIX Set new password - show additional info for which account
  server/routes/authorization.js
Labels: HOTFIX

#308 [EOC-453] Incorrect message when the sacks is archived
  client/src/modules/list/model/reducer.js
Labels: BACKLOG, BUG

#311 [EOC-462] Github fill out description and update readme
  README.md
Labels: CURRENT-SPRINT

#312 [EOC-289] Cannot close the profile menu
  client/src/common/components/Dropdown.jsx
Labels: BUG, CURRENT-SPRINT

#320 [EOC-459] Added single item, got two items on iPhone 6s Safari
  client/src/modules/list/components/Items/InputBar/InputBar.jsx
Labels: BUG, CURRENT-SPRINT

#319 [EOC-442] Notification Missing spaces between text and email address
  client/src/common/components/MessageBox.scss
  client/src/modules/notification/Notification.scss
Labels: BACKLOG, BUG

#321 [EOC-272] [BUG] Long name for the item is out of the box
  client/src/modules/list/components/Items/ListArchivedItem/ListArchivedItem.scss
Labels: BUG, CURRENT-SPRINT

#334 [EOC-476] Text to correct in EOC license file
  LICENSE
Labels: CURRENT-SPRINT

#338 [EOC-454] Cannot restore and archive item
  client/src/modules/list/components/Items/ListArchivedItem/ListArchivedItem.jsx
  client/src/modules/list/components/Items/model/actions.js
  client/src/modules/list/components/Items/model/reducer.js
  server/controllers/list.js
Labels: BUG, CURRENT-SPRINT

#342 [EOC-455][BUG] Code 404 when user archived sacks.
  client/src/modules/list/index.jsx
  client/src/modules/list/model/actions.js
Labels: BUG, CURRENT-SPRINT

#340 [EOC-375] Update breadcrumbs when updating list name via socket
  client/src/modules/list/index.jsx
Labels: BACKLOG, BUG

#343 [EOC-489] After sign in to application white page is displayed
  client/src/modules/notification/components/Notification.jsx
Labels: BUG

#344 [EOC-486] Moving item between lists ( move to option) fix
  client/src/modules/list/model/reducer.js
  server/sockets/list.js
Labels: BUG, CURRENT-SPRINT, SOCKET

#345 EOC-482 [BUG]Update members on list view when owner is removed
  server/controllers/list.js
Labels: BUG, CURRENT-SPRINT

#349 [EOC-428] Sub-pages are not opening on the top part of the site
  client/src/app/components/Layout/Layout.jsx
Labels: BUG, CURRENT-SPRINT

#350 [EOC-429] Cannot edit the name after the creates "Sacks" and "Cohorts" when user enter whitespace in name field
  client/src/common/components/FormDialog.jsx
Labels: BUG, CURRENT-SPRINT

#351 [EOC-478] [BUG] When two users work on one Sack, one change deletes the other.
  client/src/modules/cohort/components/CohortHeader.jsx
  client/src/modules/list/components/ListHeader.jsx
Labels: BACKLOG, BUG

#361 [EOC-497] Change move item to be more descriptive
  client/src/app/styles/_buttons.scss
  client/src/locales/en.json
Labels: CURRENT-SPRINT

#360 [EOC-494] Change add item placeholder to item name placeholder
  client/src/locales/en.json
Labels: CURRENT-SPRINT
