Repository sandstreamdev/eoc, pull requests merged in 2019-11, with the labels that each got.

#443 [EOC-594] Display correct text message when user is offline
  client/src/modules/list/components/Items/model/actions.js
Labels: BUG

#453 [EOC-615] Fix text alignments in item's confirmation messages
  client/src/common/components/Confirmation.scss
  client/src/modules/user/UserProfile/DeleteForm.jsx
  client/src/modules/user/UserProfile/DeleteForm.scss
Labels: BUG

#466 [FIX] Change title on Terms Of Use view (landing)
  landing/terms-of-use.html
Labels: HOTFIX

#469 [EOC-618] Fix bugs related with @2x images on production server
  landing/images/dashboard@2x.png
  landing/images/eq-icon@2x.png
  landing/images/screen-tab-1@2x.png
  landing/images/screen-tab-2@2x.png
  landing/images/screen-tab-3@2x.png
  landing/images/system-img@2x.png
Labels: BUG

#481 Fix description button styles on safari
  client/src/app/styles/_buttons.scss
Labels: BUG, HOTFIX

#482 [EOC-600] add member no gap between input and button
  client/src/app/styles/_buttons.scss
Labels: BUG

#486 [EOC-606] Fix button styles on landing
  landing/css/style.css
Labels: HOTFIX

#495 [EOC-621] Lock handler causes displaying errors in the console
  server/sockets/helpers/index.js
Labels: BUG
